# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4


trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

# steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)\app_publish"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'


# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\app_publish'
#     includeRootFolder: false
#     archiveFile: '$(Build.ArtifactStagingDirectory)\app_publish.zip'
#     replaceExistingArchive: true


# - task: DownloadBuildArtifacts@0
#   displayName: 'Download artifact'
#   inputs:
#     buildType: 'specific'
#     project: 'MVC Agile Process'
#     pipeline: 'CI Pipeline'
#     downloadType: 'single'
#     artifactName: 'drop'
#     downloadPath: '$(System.ArtifactsDirectory)'


stages:
- stage: DeployToDocker
  displayName: 'Deploy to Docker'
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download artifact'
      inputs:
        buildType: 'specific'
        project: 'MVC Agile Process'
        pipeline: 'CI Pipeline'     
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: Docker@2
      displayName: 'Build and push Docker image'
      inputs:
        containerRegistry: 'Docker Deployment' 
        repository: 'scriptsorcerer04/mvc-movie' 
        command: 'buildAndPush'
        Dockerfile: |
          FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
          WORKDIR /app
          EXPOSE 80
          
          FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
          WORKDIR /src
          COPY ["YourAspNetApp.csproj", "."]
          RUN dotnet restore "YourAspNetApp.csproj"
          COPY . .
          WORKDIR "/src"
          RUN dotnet build "YourAspNetApp.csproj" -c Release -o /app/build
          
          FROM build AS publish
          RUN dotnet publish "YourAspNetApp.csproj" -c Release -o /app/publish
          
          FROM base AS final
          WORKDIR /app
          COPY --from=publish /app/publish .
          ENTRYPOINT ["dotnet", "YourAspNetApp.dll"]
        tags: |
          $(Build.BuildNumber)

    - script: echo 'Deployment of application zip to Docker has been succeeded'
      displayName: 'Log deployment success message'



  
 



